// Cloudinary Asset URLs
// Auto-generated by uploadAssetsToCloudinary.js
// DO NOT EDIT MANUALLY - Regenerate if images are re-uploaded

module.exports = {
  // Default avatars
  DEFAULT_AVATAR: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359640/trot/images/default-avatar.jpg",
  DEFAULT_AVATAR_BACKEND: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359638/trot/default-avatars/default-avatar.jpg",
  
  // Category images
  CATEGORY_IMAGES: {
    creative: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359641/trot/images/creative.jpg",
    mentorships: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359643/trot/images/mentorships.jpg",
    music: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359645/trot/images/music.jpg",
    studies: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359647/trot/images/studies.jpg",
    competition: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359649/trot/images/competition.jpg",
    more: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359651/trot/images/more.jpg",
    technical: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359652/trot/images/technical.avif",
  },
  
  // Helper function to get category image
  getCategoryImage: (category) => {
    const categoryMap = {
      creative: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359641/trot/images/creative.jpg",
      mentorships: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359643/trot/images/mentorships.jpg",
      music: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359645/trot/images/music.jpg",
      studies: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359647/trot/images/studies.jpg",
      competition: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359649/trot/images/competition.jpg",
      more: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359651/trot/images/more.jpg",
      technical: "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359652/trot/images/technical.avif",
    };
    return categoryMap[category?.toLowerCase()] || "https://res.cloudinary.com/ducxkpytj/image/upload/v1763359651/trot/images/more.jpg";
  }
};
